name: magnetfruit_entity
version: 0.1.1
description: 'Entity definition. Used by various magnetfruit programs.'
author: Zyrthofar <zyrthofar@magnetfruit.com>
homepage: 'http://www.magnetfruit.com/entity/'