name: magnetfruit_entity
version: 0.1.4
description: 'Domain model definition. Used by various magnetfruit programs.'
author: Zyrthofar <zyrthofar@magnetfruit.com>
homepage: 'http://www.magnetfruit.com/entity/'
dependencies:
  magnetfruit_avocadorm:
    git:
      url: git://github.com/ProgrammersForABetterTomorrowYesterday/avocadorm.git
      ref: development

